# Generated by Django 2.1.1 on 2018-09-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='visible',
            field=models.NullBooleanField(),
        ),
    ]
