# Generated by Django 2.1.1 on 2018-09-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_image_filename', models.TextField()),
                ('raw_image_format', models.TextField()),
                ('cooked_image_filename', models.TextField()),
                ('cooked_image_format', models.TextField()),
            ],
        ),
    ]
