# Generated by Django 2.1.1 on 2018-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringimage',
            name='cooked_image_filename',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='monitoringimage',
            name='cooked_image_format',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='monitoringimage',
            name='raw_image_filename',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='monitoringimage',
            name='raw_image_format',
            field=models.TextField(null=True),
        ),
    ]
