# Generated by Django 2.1.1 on 2018-09-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_record_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_class', models.TextField(null=True)),
                ('image_id_begin', models.IntegerField(null=True)),
                ('image_id_end', models.IntegerField(null=True)),
                ('time_begin', models.BigIntegerField(null=True)),
                ('time_end', models.BigIntegerField(null=True)),
            ],
        ),
    ]
